---
title: "Portfolio 2"
---
The goal of this is to take my cleaned data and make graphs based on the means and se of the data. I want to make two graphs for this.


```{r load-packages, message=FALSE}
library(tidyverse) 
library(tidyr)
library(ggplot2)

```

This repeats what I did in portfolio 1.

```{r getting_cleaneddata}
ideal_society <- read.csv("C:\\Users\\Ben\\OneDrive\\Documents\\01Wake Forest\\2025SpringDataScience\\IdealSocietyData\\RRRPILOT_IdealSocietiesConservative Values_February 10, 2025_07.27.csv")

ideal_society$StartDate <- as.POSIXct(ideal_society$StartDate, format="%Y-%m-%d %H:%M:%S", tz="UTC")
```

```{r gettingdata2}

ideal_society_real_data <- ideal_society %>%
  filter(as.Date(StartDate)=="2025-01-28") %>%
  filter(Progress != 14)

ideal_society_clean <- ideal_society_real_data %>%
  filter(Q127 != 5)

```

Now I need to add political orientation data

```{r screams}
politicalorientation_data <- read.csv("C:\\Users\\Ben\\OneDrive\\Documents\\01Wake Forest\\2025SpringDataScience\\IdealSocietyData\\CopyMergefile.csv")

ideal_society_clean <- ideal_society_clean %>%
  left_join(politicalorientation_data, by = "PROLIFIC_PID")
  


```
  
 
```{r renamingpoli}
ideal_society_clean <- ideal_society_clean %>%
  rename (poli_ori = PROLIFIC_Political.spectrum..us.)

```

```{r renamingsocieties}

ideal_society_clean <- ideal_society_clean %>%
  rename(LILH = Q7) %>%
  rename(LIHH = Q4) %>%
  rename(HILH = Q6) %>%
  rename(HIHH = Q5) %>%
  rename(LTLH = Q8) %>%
  rename(LTHH = Q124) %>%
  rename(HTLH = Q125) %>%
  rename(HTHH = Q126) %>%
  rename(LRLH = Q137) %>%
  rename(LRHH = Q139) %>%
  rename(HRLH = Q140) %>%
  rename(HRHH = Q141)

```

```{r means_se}

ideal_society_clean$LTLH <- as.numeric(as.character(ideal_society_clean$LTLH))
ideal_society_clean$LTHH <- as.numeric(as.character(ideal_society_clean$LTHH))


means_and_se <-ideal_society_clean %>%
  group_by(poli_ori) %>%
  summarize(
    LTLH_mean = mean(LTLH),
    LTHH_mean = mean(LTHH),
    LTLH_se = sd(LTLH) / sqrt(n()),
    LTHH_se = sd(LTHH) / sqrt(n())
  )

```

```{r widetolong}

long_means_and_se <- means_and_se %>%
  pivot_longer(
    cols = c(LTLH_mean, LTHH_mean, LTLH_se, LTHH_se),
    names_to = c("Society_Type", "Stat"),
    names_pattern = "(LTLH|LTHH)_(mean|se)",
    values_to = "variable_value"
  )

long_means_and_se$Society_Type <- factor(long_means_and_se$Society_Type, levels = c("LTLH", "LTHH"))

```

```{r longtowide}
long_means_and_se <- long_means_and_se %>%
  pivot_wider(
    names_from = "Stat",
    values_from = "variable_value"
  )
```





```{r scatterplot}
ggplot(long_means_and_se, aes(x = Society_Type, y = mean, color = poli_ori)) +
  geom_point(position = position_dodge(width = 0.0), size = 3) +
  geom_line(aes(group = poli_ori), position = position_dodge(width = 0), size = 1)+
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), 
                width = 0.2, 
                position = position_dodge(width = 0.0)) +
 scale_color_manual(values = c("Conservative" = "red", "Liberal" = "blue")) +
   scale_y_continuous(
    limits = c(1, 11),  # Set the y-axis range from 1 to 11
    breaks = seq(1, 11, by = 1)  # Set ticks every 1 unit from 1 to 11
  ) + 
  
  labs(
    title = "Nontraditional Family Values",
    x = "Low to High Happiness",
    y = "Ideal Society Ratings",
    color = "Political Orientation"
  ) +
  theme_minimal()

```