<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 4</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 4</h1>

</div>


<pre class="r"><code>library(tidyverse) </code></pre>
<pre><code>## Warning: package &#39;tidyverse&#39; was built under R version 4.4.3</code></pre>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 4.4.3</code></pre>
<pre><code>## Warning: package &#39;purrr&#39; was built under R version 4.4.3</code></pre>
<pre class="r"><code>library(ggplot2)
library(viridis)</code></pre>
<pre><code>## Warning: package &#39;viridis&#39; was built under R version 4.4.3</code></pre>
<pre class="r"><code>palmtrees &lt;- readr::read_csv(&#39;https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-03-18/palmtrees.csv&#39;)</code></pre>
<pre><code>## Rows: 2557 Columns: 29
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (17): spec_name, acc_genus, acc_species, palm_tribe, palm_subfamily, cli...
## dbl (12): max_stem_height_m, max_stem_dia_cm, max_leaf_number, max__blade__l...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>exploratory graphs looking at the data</p>
<pre class="r"><code>palmtrees %&gt;%
  ggplot(aes(x = max_stem_height_m)) +
  geom_histogram()</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 446 rows containing non-finite outside the scale range
## (`stat_bin()`).</code></pre>
<p><img src="p04_files/figure-html/summarystats-1.png" width="672" /></p>
<pre class="r"><code>  palmtrees %&gt;%
    ggplot(aes(x = max_stem_height_m)) +
  geom_histogram()+
  facet_wrap(~palm_subfamily)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 446 rows containing non-finite outside the scale range
## (`stat_bin()`).</code></pre>
<p><img src="p04_files/figure-html/summarystats-2.png" width="672" /></p>
<pre class="r"><code>  palmtrees %&gt;%
    ggplot(aes(x = max_stem_height_m)) +
  geom_histogram()+
  facet_wrap(~fruit_shape)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 446 rows containing non-finite outside the scale range
## (`stat_bin()`).</code></pre>
<p><img src="p04_files/figure-html/summarystats-3.png" width="672" /></p>
<pre class="r"><code>   palmtrees %&gt;%
    ggplot(aes(x = max_leaf_number)) +
  geom_histogram()+
  facet_wrap(~understorey_canopy)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1251 rows containing non-finite outside the scale range
## (`stat_bin()`).</code></pre>
<p><img src="p04_files/figure-html/summarystats-4.png" width="672" /></p>
<pre class="r"><code>palmtrees %&gt;%
    ggplot(aes(x = max__blade__length_m)) +
  geom_histogram()+
  facet_wrap(~understorey_canopy)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 659 rows containing non-finite outside the scale range
## (`stat_bin()`).</code></pre>
<p><img src="p04_files/figure-html/summarystats-5.png" width="672" /></p>
<p>Based on my exploratory results I want to create some good plot to
tell a story about how canopy and understory palms differ.</p>
<p>Quick googling showed me that canopy trees are those that are taller
and receive more sunlight and wind compared to understory trees that
receive less sunlight compared to the canopy trees.</p>
<p>#hypotheses</p>
<p>Some hypotheses that I have are: 1 Canopy trees are taller than
understory trees 2 Fruit type will be different between groups
(conspicuousness) 3 <em>exploratory</em> understorey trees might have
more defenses compared to canopy trees (stem or leaves being armed)</p>
<p>#data_cleaning</p>
<pre class="r"><code>palmtrees_clean &lt;- palmtrees %&gt;%
  filter(understorey_canopy %in% c(&quot;canopy&quot;, &quot;understorey&quot;))</code></pre>
<p>#h_1_taller ##t test</p>
<pre class="r"><code>palmtrees_clean %&gt;%
  t.test(max_stem_height_m ~ understorey_canopy, data = .)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  max_stem_height_m by understorey_canopy
## t = 37.56, df = 1197.6, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means between group canopy and group understorey is not equal to 0
## 95 percent confidence interval:
##  14.78904 16.41920
## sample estimates:
##      mean in group canopy mean in group understorey 
##                 17.875108                  2.270985</code></pre>
<p>##violin_plot</p>
<pre class="r"><code>palmtrees_clean %&gt;%
  ggplot(aes(x = understorey_canopy, y = max_stem_height_m, fill = understorey_canopy)) +
  geom_violin() +
   scale_x_discrete(
    name   = &quot;Understorey vs Canopy&quot;,          
    labels = c(
      canopy      = &quot;Canopy&quot;,
      understorey = &quot;Understorey&quot;)) +
  scale_fill_viridis_d(
    name   = &quot;Type of Palm&quot;,
    labels = c(
      canopy      = &quot;Canopy&quot;,
      understorey = &quot;Understorey&quot;) ) +
  labs( y = &quot;Max Stem Height (m)&quot;, 
        title = &quot;Max Stem Height of Canopy vs Understorey Palms&quot;) +
  theme_classic()</code></pre>
<pre><code>## Warning: Removed 183 rows containing non-finite outside the scale range
## (`stat_ydensity()`).</code></pre>
<p><img src="p04_files/figure-html/height_violin_plot-1.png" width="672" /></p>
<p>##conclusion Yes, the canopy palms appear to be much taller compared
to the understorey palms. On average they are 14.78904 to 16.41920 (95%
CI) meters taller.</p>
<p>#h_2_fruit ##testing_proportion</p>
<pre class="r"><code>tbl &lt;- table(
  palmtrees_clean$understorey_canopy,
  palmtrees_clean$conspicuousness
)
prop.table(tbl, margin = 1)</code></pre>
<pre><code>##              
##               conspicuous   cryptic
##   canopy        0.3505462 0.6494538
##   understorey   0.4700855 0.5299145</code></pre>
<pre class="r"><code>prop.test(
  x = c(
    tbl[&quot;canopy&quot;,      &quot;conspicuous&quot;],    # successes in canopy
    tbl[&quot;understorey&quot;, &quot;conspicuous&quot;]     # successes in understory
  ),
  n = c(
    sum(tbl[&quot;canopy&quot;, ]),                 # total canopy palms
    sum(tbl[&quot;understorey&quot;, ])             # total understory palms
  )
)</code></pre>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(tbl[&quot;canopy&quot;, &quot;conspicuous&quot;], tbl[&quot;understorey&quot;, &quot;conspicuous&quot;]) out of c(sum(tbl[&quot;canopy&quot;, ]), sum(tbl[&quot;understorey&quot;, ]))
## X-squared = 24.14, df = 1, p-value = 8.959e-07
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.16798814 -0.07109044
## sample estimates:
##    prop 1    prop 2 
## 0.3505462 0.4700855</code></pre>
<p>##bar_plot</p>
<pre class="r"><code>palmtrees_clean %&gt;%
  filter(
    understorey_canopy %in% c(&quot;canopy&quot;, &quot;understorey&quot;),
    !is.na(conspicuousness)
  ) %&gt;%
  ggplot(aes(x = understorey_canopy, fill = conspicuousness, na.rm = TRUE)) +
  geom_bar(position = &quot;fill&quot;) +
  scale_x_discrete(
    name   = &quot;Understorey vs Canopy&quot;,          
    labels = c(
      canopy      = &quot;Canopy&quot;,
      understorey = &quot;Understorey&quot;)) +
  scale_fill_viridis_d(
    name   = &quot;Conspicuousness&quot;,
    labels = c(
      conspicuous      = &quot;Conspicuous&quot;,
      inconspicuous = &quot;Inconspicuous&quot;) ) +
  labs( y = &quot;Proportion of Palms&quot;, 
        title = &quot;Proportion of Conspicuousness of Canopy vs Understorey Palms&quot;) +
  theme_classic()</code></pre>
<p><img src="p04_files/figure-html/fruit_bar_plot-1.png" width="672" /></p>
<p>##conclusion</p>
<p>There is a statistically significant difference in the proportion of
conspicuous fruit between canopy and understorey palms. Understorey
palms are more likely to have conspiciuous fruit–meaning they are
brighter in color–compared to canopy palms who are more likely to have
cryptic fruit–colors making them harder to see.</p>
<p>This might be because understorey palms may be in darker
environments, meaning that they need to have brighter colored fruit in
order to disperse their seeds where bright colors are not as
adventatgeous in the canopy regions.</p>
<p>#h_3_defense ##proportions</p>
<pre class="r"><code>#stem
tbl1 &lt;- table(
  palmtrees_clean$understorey_canopy,
  palmtrees_clean$stem_armed)

prop.table(tbl1, margin = 1)</code></pre>
<pre><code>##              
##                    armed  non-armed
##   canopy      0.89684373 0.10315627
##   understorey 0.93162393 0.06837607</code></pre>
<pre class="r"><code>prop.test(
  x = c(
    tbl1[&quot;canopy&quot;,      &quot;armed&quot;],    
    tbl1[&quot;understorey&quot;, &quot;armed&quot;]     
  ),
  n = c(
    sum(tbl1[&quot;canopy&quot;, ]),           
    sum(tbl1[&quot;understorey&quot;, ])       
  )
)</code></pre>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(tbl1[&quot;canopy&quot;, &quot;armed&quot;], tbl1[&quot;understorey&quot;, &quot;armed&quot;]) out of c(sum(tbl1[&quot;canopy&quot;, ]), sum(tbl1[&quot;understorey&quot;, ]))
## X-squared = 7.7252, df = 1, p-value = 0.005446
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.05882992 -0.01073049
## sample estimates:
##    prop 1    prop 2 
## 0.8968437 0.9316239</code></pre>
<pre class="r"><code>#leaf
tbl2 &lt;- table(
  palmtrees_clean$understorey_canopy,
  palmtrees_clean$leaves_armed)

prop.table(tbl2, margin = 1)</code></pre>
<pre><code>##              
##                   armed non-armed
##   canopy      0.4555133 0.5444867
##   understorey 0.7139738 0.2860262</code></pre>
<pre class="r"><code>prop.test(
  x = c(
    tbl2[&quot;canopy&quot;,      &quot;armed&quot;],    
    tbl2[&quot;understorey&quot;, &quot;armed&quot;]     
  ),
  n = c(
    sum(tbl2[&quot;canopy&quot;, ]),           
    sum(tbl2[&quot;understorey&quot;, ])       
  )
)</code></pre>
<pre><code>## 
##  2-sample test for equality of proportions with continuity correction
## 
## data:  c(tbl2[&quot;canopy&quot;, &quot;armed&quot;], tbl2[&quot;understorey&quot;, &quot;armed&quot;]) out of c(sum(tbl2[&quot;canopy&quot;, ]), sum(tbl2[&quot;understorey&quot;, ]))
## X-squared = 145.45, df = 1, p-value &lt; 2.2e-16
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.2991478 -0.2177731
## sample estimates:
##    prop 1    prop 2 
## 0.4555133 0.7139738</code></pre>
<p>##bar_plot</p>
<pre class="r"><code>palmtrees_clean %&gt;%
  filter(
    understorey_canopy %in% c(&quot;canopy&quot;, &quot;understorey&quot;),
    !is.na(leaves_armed)
  ) %&gt;%
  ggplot(aes(x = understorey_canopy, fill = leaves_armed, na.rm = TRUE)) +
  geom_bar(position = &quot;fill&quot;) +
  scale_x_discrete(
    name   = &quot;Understorey vs Canopy&quot;,          
    labels = c(
      canopy      = &quot;Canopy&quot;,
      understorey = &quot;Understorey&quot;)) +
  scale_fill_viridis_d(
    name   = &quot;Leaves Armed&quot;,
    labels = c(
      armed      = &quot;Armed&quot;,
      unarmed = &quot;Unarmed&quot;) ) +
  labs( y = &quot;Proportion of Palms&quot;, 
        title = &quot;Proportion of Leaves Armed of Canopy vs Understorey Palms&quot;) +
  theme_classic()</code></pre>
<p><img src="p04_files/figure-html/armedbarplot-1.png" width="672" /></p>
<p>##violinplot_armedxheight</p>
<pre class="r"><code>palmtrees_clean %&gt;%
  filter(
    leaves_armed %in% c(&quot;armed&quot;, &quot;non-armed&quot;),
    !is.na(max_stem_height_m)
  ) %&gt;%
  
  mutate(
    leaves_armed = factor(leaves_armed, levels = c(&quot;non-armed&quot;,&quot;armed&quot;))
  ) %&gt;%
  ggplot(aes(
    x    = leaves_armed,
    y    = max_stem_height_m,
    fill = leaves_armed
  )) +
    geom_violin(trim = FALSE) +
    scale_x_discrete(
      name   = &quot;Leaves Armed&quot;,
      labels = c(&quot;non-armed&quot; = &quot;Non-armed&quot;, &quot;armed&quot; = &quot;Armed&quot;)
    ) +
    scale_fill_viridis_d(
      name   = &quot;Leaf Armour&quot;,
      labels = c(&quot;Non-armed&quot;, &quot;Armed&quot;)
    ) +
    labs(
      y     = &quot;Max Stem Height (m)&quot;,
      title = &quot;Distribution of Stem Height by Leaf Armament&quot;
    ) +
    theme_classic()</code></pre>
<p><img src="p04_files/figure-html/correlation-1.png" width="672" /></p>
<p>##conclusion</p>
<p>understorey palms seem to be more likely to have stem armour (p =
.005) and leaf armour (p &lt; .001). Leaf armour also is more common for
shorter palms, supporting this hypothesis.</p>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
